# Generated by Django 4.2.4 on 2023-08-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_aboutmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
