# Generated by Django 4.2.4 on 2023-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projectmodel_file_alter_projectmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='url_to_project',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
